apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort:  {{ .Values.service.internalPort }}        
#  - name: http  
#    port: {{ .Values.service.servicePort }}
  selector:
    app: "{{  .Chart.Name }}-selector"
